### PR TITLE
Add: realize.rs, this is now ok to merge

### LINKED ISSUE #18: Implement realize.rs
I'm currently exploring the datatypes and functions used in the python code. I am doing this for the dtypes file but I thought it was a good idea to use it to fix realize.rs first since its only two lines.

### PR DESCRIPTION
**Pull request by 21st-centuryman**
Just a little log of the stuff I have done so far as well as documentation.

closes #18

### CODE REVIEW

**Comment by 21st-centuryman** [comment]
closes #18

**Comment by 21st-centuryman** [comment]
So there is no equivilant to the python `pass` in rust, instead we should just throw an error if it doesn't work.

**Comment by 21st-centuryman** [comment]
Ok so i think I am mostly correct with `run_schedule`. Since they are simply doing a pass i think we can treat this code as a test case for now. Ie if `disable_logging` is true, run error.  The only issue with `run_schedule` is the type of the schedule, and something I will probably explore tomorrow. It seems to be a class in tinygrad proper.


For `create_schedule` the function should and ough to return an empty vector. What type that vector will be is undecided. The return type should be the same as the `schedule` variable in `run_schedule`, as noted by the only mention of these functions in `tensor.py`
```python
run_schedule(create_schedule(flatten([x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata] for x in lst])))
``` 

Yes this is all we are working with.

**Comment by 21st-centuryman** [comment]
or to make it prettier:

```python
run_schedule(
    create_schedule(
        flatten([
            x.lazydata.lbs if isinstance(x.lazydata, MultiLazyBuffer) else [x.lazydata]
            for x in lst
        ])
    )
)
```

**Comment by 21st-centuryman** [comment]
ok plz ignore what i talked about before, the python code just made me hella confused. i made the code properly now. This should be all the code does. 

Flatten returns a `vec<i32>` so we will get that as our input for `create_schedule` (not that it matters, but I believe it will matter later) and it will be the same for `run_schedule`

**Comment by 21st-centuryman** [comment]
Compressed it too. i know we will not do that until the end of the project but I don't wanna touch this file again

**Comment by 21st-centuryman** [comment]
closes #18

**Review by Jakunot — APPROVED** [review]
LGTM

**Pull request merged**
